version: '3.9'
services:
  web:
    build: .
    container_name: site-web
    expose:
      - "3000"
  nginx:
    image: nginx:alpine
    container_name: site-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - web
