repository:
  description: "Next.js site with Gitflow automation"
  topics: [nextjs, ci, cd, docker, ghcr]
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

labels:
  - { name: codex,   color: "5319e7", description: "Codex automation" }
  - { name: ci,      color: "0e8a16", description: "CI/CD" }
  - { name: release, color: "1d76db", description: "Release" }
  - { name: infra,   color: "d93f0b", description: "Infra/DevOps" }

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts: ["lint", "test", "build"]
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      allow_force_pushes: false
      allow_deletions: false

  - name: release
    protection:
      required_status_checks:
        strict: true
        contexts: ["lint", "test", "build"]
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
      allow_force_pushes: false
      allow_deletions: false

  - name: stage
    protection:
      required_status_checks:
        strict: true
        contexts: ["lint", "test", "build"]
      allow_force_pushes: false
      allow_deletions: false

  - name: deployments
    protection:
      required_status_checks:
        strict: true
        contexts: ["lint", "test", "build"]
      allow_force_pushes: false
      allow_deletions: false
