name: Bug report
description: Report a bug
labels: [ci]
body:
  - type: textarea
    id: steps
    attributes: { label: Steps to reproduce, placeholder: "1) ... 2) ... 3) ..." }
    validations: { required: true }
  - type: input
    id: sha
    attributes: { label: Commit SHA }
  - type: input
    id: env
    attributes: { label: Environment (local/stage/release) }
