name: Feature Request
description: Suggest a new idea
labels: [enhancement]
title: "feat: "
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What would you like to see added?
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Why?
      description: Why is this feature useful?
  - type: textarea
    id: notes
    attributes:
      label: Additional info
      description: Anything else you'd like to mention?
