name: Task
description: New task
title: "[Task]: "
labels: [task]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What needs to be done?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Optional details
