name: CI

on:
  push:
    branches:
      - main
      - deployments
      - stage
      - release
      - 'codex/*'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run lint
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run tests
        run: yarn test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build project
        run: yarn build

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t personal-site .

  promote:
    runs-on: ubuntu-latest
    needs: docker
    if: |
      startsWith(github.ref, 'refs/heads/codex/') ||
      github.ref == 'refs/heads/deployments' ||
      github.ref == 'refs/heads/stage' ||
      github.ref == 'refs/heads/release'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Promote to next branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "$GITHUB_REF" == refs/heads/codex/* ]]; then
            feature="${GITHUB_REF#refs/heads/codex/}"
            git push origin HEAD:features/${feature}
            gh pr create --head features/${feature} --base deployments --title "Promote ${feature} to deployments" --body "Automated PR from codex to deployments"
          elif [[ "$GITHUB_REF" == "refs/heads/deployments" ]]; then
            gh pr create --head deployments --base stage --title "Deployments to Stage" --body "Automated PR from deployments to stage"
          elif [[ "$GITHUB_REF" == "refs/heads/stage" ]]; then
            gh pr create --head stage --base release --title "Stage to Release" --body "Automated PR from stage to release"
          elif [[ "$GITHUB_REF" == "refs/heads/release" ]]; then
            gh pr create --head release --base main --title "Release to Main" --body "Automated PR from release to main"
          fi
