name: Pages – deploy (main → gh-pages)
on:
    push:
        branches: [main]

permissions:
    contents: write

concurrency:
    group: pages-prod
    cancel-in-progress: true

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js 22
              uses: actions/setup-node@v4
              with:
                  node-version: '22'

            - name: Install deps
              env:
                  HUSKY: 0
              run: |
                  corepack enable
                  if [ -f pnpm-lock.yaml ]; then pnpm i --frozen-lockfile; \
                  elif [ -f yarn.lock ]; then yarn --frozen-lockfile; \
                  else npm ci; fi

            - name: Build static site (Next.js export if used)
              env:
                  NEXT_TELEMETRY_DISABLED: 1
              run: |
                  if [ -f package.json ] && jq -e '.scripts.export' package.json >/dev/null 2>&1; then \
                    npm run build --if-present || true
                    npm run export
                  else
                    npm run build --if-present
                  fi

            - name: Deploy to gh-pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  branch: gh-pages
                  folder: out
                  force: false
                  clean: true
                  clean-exclude: |
                      pr-preview/
