name: Pages – PR preview
on:
    pull_request:
        types: [opened, reopened, synchronize, closed]

permissions:
    contents: write

concurrency:
    group: pages-preview-${{ github.ref }}
    cancel-in-progress: true

jobs:
    preview:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js 22
              uses: actions/setup-node@v4
              with:
                  node-version: '22'

            - name: Install deps
              if: github.event.action != 'closed'
              env:
                  HUSKY: 0
              run: |
                  corepack enable
                  if [ -f pnpm-lock.yaml ]; then pnpm i --frozen-lockfile; \
                  else yarn install; fi

            - name: Build static site (Next.js export if used)
              if: github.event.action != 'closed'
              env:
                  NEXT_TELEMETRY_DISABLED: 1
              run: |
                  if [ -f package.json ] && jq -e '.scripts.export' package.json >/dev/null 2>&1; then \
                    npm run build --if-present || true
                    npm run export
                  else
                    npm run build --if-present
                  fi

            - name: Deploy/remove PR preview
              uses: rossjrw/pr-preview-action@v1
              with:
                  source-dir: ./out/
