name: Trivy Security Scan
on:
  push:
    branches: [main, release, stage, deployments]
  pull_request:
    branches: [main, release, stage, deployments]

permissions:
  contents: read

jobs:
  fs:
    name: FS Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          ignore-unfixed: true
          format: table
          severity: CRITICAL,HIGH

  image:
    name: Image Scan
    runs-on: ubuntu-latest
    needs: fs
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          push: false
          load: true
          tags: site:ci-scan
      - uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: site:ci-scan
          format: table
          ignore-unfixed: true
          severity: CRITICAL,HIGH
